---
- hosts: all
  become: yes
  tasks:
          - name: update apt list
            apt:
                  update_cache: yes
          - name: install packages
            action: apt pkg={{ item }} state=latest
            with_items:
                    - php-mysqli
