---
- hosts: all
  remote_user: ansible
  become: yes
  roles:
          - '/home/ansible/.ansible/roles/oefenweb.wordpress'
  vars:
          wordpress_installs:
                  - name: wordpress
                    dbname: wordpress
                    dbuser: wordpress
                    dbpass: 'password'
                    dbhost: localhost
                    path: /var/www
                    url: http://localhost
                    title: wordpress
                    admin_name: admin
                    admin_email: root@localhost.localdomain
                    admin_password: 'password'
                    themes:
                            - name: twentytwelve
                              activate: true
                            - name: twentythirteen
                    plugins:
                            - name: contact-form-7
                              activate: false
                            - name: simple-fields
                    users: {}
                    options: []
                    queries: []
